version: "2"
# volumes:
#   store:
#     external: true
#     name: store

services:
  db:
    image: mysql:8.0
    restart: always
    env_file: ./db/.env
    container_name: agent_mysql
    ports:
      - 3306:3306
    tty: true #-it 대화형 허용
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  back:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    # volumes:
    #   - store:/store
    depends_on:
      db:
        condition: service_healthy
    tty: true
    env_file: ./server/.env
    container_name: fastapi_server
    command: uvicorn --host 0.0.0.0 api.api:app
    ports:
      - 8000:8000
    volumes:
      - /path/to/data:/data
  
  front:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    container_name: react_client
    depends_on:
      back:
        condition: service_healthy
    command: npm run start
    ports:
      - 3000:3000