version: "2"

# https://velog.io/@k0310kjy/nginx-react-fast-api-docker-compose-%EA%B5%AC%EC%84%B1%ED%99%98%EA%B2%BD-%EB%B3%80%EC%88%98-%EB%AC%B8%EC%A0%9C-%ED%95%B4%EA%B2%B0
services:
  db:
    image: mysql:8.0
    restart: always
    container_name: chatdb
    ports:
      - 3307:3306
    tty: true #-it 대화형 허용
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Seoul
    volumes:
      - ./db/:/docker-entrypoint-initdb.d
    platform: linux/x86_64
  
  back:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./store:/store
      - ./html_store:/html_store
    depends_on:
      - db
    tty: true
    env_file: ./server/.env
    container_name: fastapi_server
    command: uvicorn --host 0.0.0.0 api.api:app
    ports:
      - 8000:8000
  
  front:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    container_name: react_client
    depends_on:
      - back
    command: npm run start
    ports:
      - 3000:3000
    networks:
      - chosen-network

networks:
  chosen-network:
    driver: bridge

volumes:
  data01:
    driver: local