version: "2"


services:
  db:
    image: mysql:8.0
    restart: always
    container_name: chatdb
    ports:
      - 3307:3306
    tty: true #-it 대화형 허용
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Seoul
    volumes:
      - ./db/:/docker-entrypoint-initdb.d
    platform: linux/x86_64
  back:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./store:/store
    depends_on:
      db:
        condition: service_healthy
    tty: true
    env_file: ./server/.env
    container_name: fastapi_server
    command: uvicorn --host 0.0.0.0 api.api:app
    ports:
      - 8000:8000
  
  front:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    container_name: react_client
    depends_on:
      back:
        condition: service_healthy
    command: npm run start
    ports:
      - 3000:3000